### ISSUE TITLE
DB Migration Problem

### ISSUE THREAD

**Issue by kalyanmondal** [dotnet-architecture/eShopOnWeb#297] opened 2019-09-09 10:18 UTC
After following below steps as stated under "Running the Sample"

Configuring the sample to use SQL Server
Update Startup.cs's ConfigureDevelopmentServices method as follows:
        public void ConfigureDevelopmentServices(IServiceCollection services)
        {
            // use in-memory database
            //ConfigureTestingServices(services);

            // use real database
            ConfigureProductionServices(services);

        }
Ensure your connection strings in appsettings.json point to a local SQL Server instance.

Open a command prompt in the Web folder and execute the following commands:

dotnet restore
dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
These commands will create two separate databases, one for the store's catalog data and shopping cart information, and one for the app's user credentials and identity data.

Run the application.

I am getting the below error

A database operation failed while processing the request.
SqlException: Invalid object name 'CatalogBrand'.
There are pending model changes for CatalogContext
In Visual Studio, use the Package Manager Console to scaffold a new migration for these changes and apply them to the database:

PM> Add-Migration [migration name]
PM> Update-Database
Alternatively, you can scaffold a new migration and apply it from a command prompt at your project directory:

> dotnet ef migrations add [migration name]
> dotnet ef database update

![Capture](https://user-images.githubusercontent.com/11206967/64523119-377b9580-d319-11e9-926c-ce61eb778cab.JPG)

**Comment by efleming18** [comment] 2019-09-10 17:23
Hey @kalyanmondal - I will get a response out to you this afternoon/evening after taking a look.

**Comment by efleming18** [comment] 2019-09-11 01:15
Hey @kalyanmondal - I was able to reproduce the issue. It looks like after some modeling updates, I forgot to run / add another migration. I've added it in PR https://github.com/dotnet-architecture/eShopOnWeb/pull/298 which seems to fix everything. I'll have @ardalis review it and see if we can get it merged soon for you. Thanks for raising the issue!

**Comment by kalyanmondal** [comment] 2019-09-11 08:20
Hello @efleming18 I pulled the branch and run locally. It is working fine.
Thank you for your help.

**Comment by efleming18** [comment] 2019-09-11 13:50
Great to hear @kalyanmondal! The PR has been merged in to master now as well.

**Closed by efleming18** 2019-09-11 13:50 UTC
