### ISSUE TITLE
Separate Baskets before and after login on the same tab.

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#401] opened 2020-06-17 16:37 UTC
I add a few items to the basket anonymously.

After logging in on the same browser tab, it empties my basket.
After logging out, I see my anonymously added basket items.
When I log in again, I see the basket items which I had added while logged in.

Is this an intended behavior?

**Comment by efleming18** [comment] 2020-06-18 00:58
Definitely not intended behavior @yigith - I actually believe there was a PR to address that issue not too long ago. Let me check on it.

**Comment by efleming18** [comment] 2020-06-18 01:13
Looking back, this was partially fixed by @michelcedric in the past but a small piece of it must have been lost in a bad merge somewhere. The scenario he fixed is if you add items to your cart (not logged in) and click "Checkout" it will prompt you to login. Once you've logged in, the checkout will continue and your order will be under the account you logged in with - as expected.

The scenario you describe is still an issue though. Would you or @michelcedric be interested in opening a PR to address it? As always, I'm happy to work on it if not.

**Comment by yigith** [comment] 2020-06-18 08:07
> Looking back, this was partially fixed by @michelcedric in the past but a small piece of it must have been lost in a bad merge somewhere. The scenario he fixed is if you add items to your cart (not logged in) and click "Checkout" it will prompt you to login. Once you've logged in, the checkout will continue and your order will be under the account you logged in with - as expected.
> 
> The scenario you describe is still an issue though. Would you or @michelcedric be interested in opening a PR to address it? As always, I'm happy to work on it if not.

After clicking checkout, it redirects me to login page and after logging in, it redirects me back to a thank you page saying: 

> Thanks for your Order!
> Continue Shopping...

and it empties my basket. So without any further user confirmation, the order is being placed. (It seemed wrong but i thought it had demonstration purposes)

I can work on this, my approach would be like the following:

ON LOGIN:
- transfer the anonymous basket items without deleting the existing items on the user basket.
(The user might have added some basket items on another browser/device before or on a previous login)
- after transfer, delete the anonymous basket and basket cookie so that if the user logs out, the user should have privacy concerns. Besides, the user's basket items are still preserved in his/her account)

THINGS TO CHECK:
- while the user is logged in, basket cookie shouldn't be created or exist. Even if it exists, it should be ignored.
- when the user logs out, no anonymous basket items should be left (neither cookie nor db item)

So do you think this would be a good way to proceed with?

**Comment by efleming18** [comment] 2020-06-18 20:50
Hey @yigith - that approach sounds good to me! 

Additionally your comment here:
>and it empties my basket. So without any further user confirmation, the order is being placed. (It seemed wrong but i thought it had demonstration purposes)

I would definitely be open to it being more of this flow:
- User adds items to basket (not logged in)
- They navigate to the basket
- Click "Checkout"
- Prompt for them to login
- After login, redirect back to the Basket screen so they can push "Checkout" again.
This way it's a little more friendly for the user to really confirm they want to checkout after logging in. Not required in the same PR as the changes above, but I would be open to that for sure.

**Comment by yigith** [comment] 2020-06-18 23:17
> I would definitely be open to it being more of this flow:
> 
> * User adds items to basket (not logged in)
> * They navigate to the basket
> * Click "Checkout"
> * Prompt for them to login
> * After login, redirect back to the Basket screen so they can push "Checkout" again.
>   This way it's a little more friendly for the user to really confirm they want to checkout after logging in. Not required in the same PR as the changes above, but I would be open to that for sure.

I totally agree. Additionally, on the basket page after clicking "Checkout", we can take the user to a [Authorized] "Review/Checkout" page which will be redirect to login page automatically if not logged in. After logging in, it will return to Review/Checkout page where the user can see the read-only version of the basket info so that s/he can review the shopping items and total price one last time before the payment transactions take place. (In the future editions, on this review page, if wanted, shipping and payment details can be asked to input.)

I am sending this link (https://getbootstrap.com/docs/4.0/examples/checkout/) in order to be clear about what i mean by a review/checkout page. (not the CSS part, just the context). 

Do you think a review/checkout page after the basket page could be a good idea before the payment and saving order process? 

By the way, I can happily work on the tasks mentioned under this issue tomorrow and at the weekend if that's OK :) Thanks.

**Comment by efleming18** [comment] 2020-06-20 00:22
@yigith I am really liking the idea of a review/checkout page! Definitely proceed with that. Looking forward to reviewing it. 

As you're working through it, if you'd like me to start reviewing it sooner rather than later feel free to open up a draft PR and tag me in it.

**Comment by efleming18** [comment] 2020-06-25 00:49
Further resolved by PR attached.

**Closed by efleming18** 2020-06-25 00:49 UTC
Labels: bug
