### ISSUE TITLE
Database Context in Presentation Layer, Why?

### ISSUE THREAD

**Issue by arvand** [dotnet-architecture/eShopOnWeb#25] opened 2017-08-06 10:31 UTC
Can somebody say why is the CatalogContext defined in the Web project? 
This is related to the Data Access Layer and I don't see why in a sample application it is in Presentation Layer.

**Comment by ardalis** [comment] 2017-08-06 16:03
It's a holdover from the original starting point of the project. You're correct it will be in a separate project once the sample is released (which should be very soon). I'll leave this issue open to track this change (moving the dbcontext).

**Comment by arvand** [comment] 2017-08-06 19:50
Do accept a pull request in which I implement the repository pattern with unit of work by using dapper and its extensions?
I am suggesting to use dapper because entity framework tends to get really slow in most scenarios and it is better to a have sample by using dapper which is practical.

**Comment by ardalis** [comment] 2017-08-07 19:30
@arvand I'm not opposed to Dapper but in this case EF is pretty much fully implemented and should work fine. I would be happy to accept a PR that showed how easy it is to use Dapper instead of EF as the repository implementation. To do this you should basically just be able to add a new generic repository that  implements IRepository<T> (just like EfRepository). Alternately, since creating a generic Dapper-based repo may be difficult, you could simply implement separate specific Dapper repositories for each kind of entity. Feel free to comment here with your thoughts prior to submitting a PR.

**Closed by ardalis** 2017-08-07 19:30 UTC

**Comment by CESARDELATORRE** [comment] 2017-08-07 19:40
I agree with Steve. We'll be willing to accept additional features/possibilities being added in a decoupled way (Open/Close Principle) in SOLID, but not removing EF Core.
Also, EF Core is a lot faster than regular EF, so I don't think we should forget about it.
In eShopOnContainers, like in the Ordering microservice, we're using Dapper for the Queries and EF Core for the DDD transactions. However, that approach requires to use a simplified CQRS approach.

**Comment by arvand** [comment] 2017-08-08 08:05
@ardalis I am not saying that EF doesn't work. It's just that as soon as the project grows you are hit with performance issues, especially for read queries. I think this is why  projects like StackOverflow and Orchad have moved to using Dapper.  (There's even a discussion on [Nopcommerce ](https://github.com/nopSolutions/nopCommerce/issues/239)to move the ORM to Dapper)

It may be hard to create a generic repository by using only Dapper, but we had great success with using FastCrud which is an extension for Dapper and it is really fast.
Also I don't think creating a generic repository will be a good idea since you have to create extension methods for extending each repository and that is not a good approach for large applications. (But there is good sample created by JetBrains [here ](https://genericunitofworkandrepositories.codeplex.com/) for using EF with UOW)

@CESARDELATORRE Great project, thank you.
I could not find a link to compare the performance of EF vs EF core. Could you please provide a source?

**Comment by CESARDELATORRE** [comment] 2017-08-08 21:58
@arvand What you say might be true for regular EF in .NET Framework. But EF Core was re-written from scratch and one of the main goals was to drastically improve performance and have a much lighter ORM than EF.
I was told by the EF Core team about that. I'll ask them about comparisons.

What you say "It's just that as soon as the project grows you are hit with performance issues with EF, especially for read queries", have you confirmed that for EF Core or just for EF? - IT is like talking about different products, really. In our case, we're using EF Core.

**Comment by arvand** [comment] 2017-08-09 06:47
@CESARDELATORRE I found these two links: [1](https://frankdecaire.blogspot.co.uk/2016/09/entity-framework-core-10-smackdown.html) , [2](https://github.com/aspnet/EntityFramework/issues/7978) 
I don't see much difference.

**Comment by CESARDELATORRE** [comment] 2017-08-09 16:16
I don't think those are very reliable posts. One is about EF Core 1, released one year ago. The second couldn't repro again if you read until the end of the post.
I'm asking the EF team and will come back, ok?

**Comment by yarrgh** [comment] 2017-08-09 20:03
This may be more relevant: [Entity Framework Core 2.0 vs. Dapper performance benchmark, querying SQL Azure tables](https://koukia.ca/entity-framework-core-2-0-vs-dapper-net-performance-benchmark-querying-sql-azure-tables-7696e8e3ed28). 

Outcome: Dapper barely wins, performance wise. If you added FastCrud, EntityFramework may actually perform better.

It does, however, compare EF 2.0 instead of EF 1.1. Good idea of how things will be with EF 2.0

**Comment by CESARDELATORRE** [comment] 2017-08-09 21:03
We're actually migrating eShopOnContainers to .NET Core 2. After August/September, the maintened branch will only be the .NET Core 2 version of eShopOfContainers.
So, EF Core 2 benchmarks apply to our roadmap. :)

**Comment by CESARDELATORRE** [comment] 2017-08-09 21:06
And in any case, we're also using Dapper for the simplified  CQRS at eShopOnContainers within the Ordering container.
Btw, I forgot to mention that, of course, we'll be migrating eShopOnWeb to .NET Core 2 during Aug. and Sept. Not just eShopOnContainers. :)

**Comment by arvand** [comment] 2017-08-19 07:35
That is great news, tnx for the news.

**Comment by JiGiBallS** [comment] 2018-11-13 08:33
> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

>

**Comment by krs99** [comment] 2018-11-19 02:59
Any news regarding decoupled DAL from UI in startup class? Is there any options to use IoC container without tighlty coupled these layers?
