### ISSUE TITLE
Error when launching web project

### ISSUE THREAD

**Issue by ElAmen** [dotnet-architecture/eShopOnWeb#100] opened 2018-06-03 14:08 UTC
InvalidOperationException: Scheme already exists: Identity.Application
Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(string name, Action<AuthenticationSchemeBuilder> configureBuilder)
Kindly help. Thanks

**Comment by ardalis** [comment] 2018-06-03 14:58
Which project are you running, Web or RazorPages? Are you getting this on app startup, on some page, or when trying to run migrations? Help me help you... :)

**Comment by ardalis** [comment] 2018-06-04 18:29
Can you confirm you have installed the ASP.NET Core 2.1 SDK? ASP.NET Core 2.1 introduced support for Razor Pages to search in the `/Pages/Shared/` folder for shared Razor files, like `_Layout.cshtml`. The reason it's no longer in the root `/Pages/` folder is that it's now in the `/Pages/Shared/` folder, which works fine when running 2.1 (as far as I can tell).

**Comment by ElAmen** [comment] 2018-06-05 10:30
I have installed ASP.NET Core 2.1 before opening the project nevertheless I had to create the layout before it could run.
I am more interested in the Web Project as my main focus is MVC. Kindly help me with the identity issue:
InvalidOperationException: Scheme already exists: Identity.Application
Thank you

**Comment by ardalis** [comment] 2018-06-05 12:54
I think the last PR merged into master addressed the `_Layout.cshtml` issue.

**Comment by mtugnoli** [comment] 2018-06-05 13:24
I have the same error (I have installed ASP.NET Core 2.1 SDK)

**Comment by ardalis** [comment] 2018-06-05 14:57
Please provide full stack trace and/or a screenshot of the message. I'd like to reproduce the issue but am not seeing (testing it on multiple machines). I've tried with both Kestrel and IIS Express hosts and both work fine. Did you follow the instructions here? https://github.com/dotnet-architecture/eShopOnWeb/blob/master/README.md

Specifically:

> Open a command prompt in the Web folder and execute the following commands:

> 
> dotnet restore
> dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
> dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
> These commands will create two separate databases, one for the store's catalog data and shopping cart information, and one for the app's user credentials and identity data.
> 
> Run the application. The first time you run the application, it will seed both databases with data such that you should see products in the store, and you should be able to log in using the demouser@microsoft.com account.

**Comment by ardalis** [comment] 2018-06-05 15:03
I may have found the problem. Are you modifying this code?

```
        public void ConfigureDevelopmentServices(IServiceCollection services)
        {
            // use in-memory database
            ConfigureInMemoryDatabases(services);

            // use real database
            // ConfigureProductionServices(services);

            ConfigureServices(services);
        }
```
by uncommenting the call to ConfigureProductionServices() ? If so, you need to then comment out the call to ConfigureServices because ConfigureProductionServices calls that, too (and you can't run it twice). Please confirm. I'll update so it's less confusing.

**Comment by ardalis** [comment] 2018-06-05 15:58
Try getting latest from `master` and re-follow the instructions in the README and see if it works now. I'm 99% sure the issue was that `ConfigureServices` was running twice, and hence `AddIdentity` was running twice.

**Closed by ardalis** 2018-06-05 15:58 UTC

**Comment by atiq-cs** [comment] 2018-06-09 03:01
I got following error after launching first time,

    HTTP Error 502.5 - Process Failure

    Common causes of this issue:
    The application process failed to start
    The application process started but then stopped
    The application process started but failed to listen on the configured port

    Troubleshooting steps:
    Check the system event log for error messages
    Enable logging the application process' stdout messages
    Attach a debugger to the application process and inspect

    For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681

screenshot,
![error_502](https://user-images.githubusercontent.com/7858031/41187030-b95c23b6-6b56-11e8-96d4-4a594d1260fc.png)

It got fixed after I installed .net core 2.1 SDK.
