### ISSUE TITLE
Errors when trying to create databases

### ISSUE THREAD

**Issue by AndrzejWroGM** [dotnet-architecture/eShopOnWeb#90] opened 2018-04-28 15:03 UTC
Hello, 
When trying to create databases by using this commands 

> Open a command prompt in the Web folder and execute the following commands:
> dotnet restore
> dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
> dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj

I have following errors in powershel with migrations. Any advice for this issue?
![2018-04-28 1](https://user-images.githubusercontent.com/24229704/39397832-eb240b32-4b05-11e8-81ef-9a9ed65285bb.png)
![2018-04-28 2](https://user-images.githubusercontent.com/24229704/39397835-f98cd7d0-4b05-11e8-9ed3-0b0aba186702.png)

**Comment by AnCze** [comment] 2018-05-01 09:30
Really no one can help solve this problem?

**Comment by ardalis** [comment] 2018-05-20 15:42
It appears you have an older version of SQL Server installed: https://stackoverflow.com/questions/7999448/sql-server-2008-express-edition-how-to-create-a-sequence

SEQUENCE is introduced in Sql Server 2012, I believe. Can you confirm what version of SQL Server you have installed and are you able to update to a more current version?

**Comment by ardalis** [comment] 2018-05-23 14:04
Closing - let me know if the issue isn't solved by a more recent SQL install.

**Closed** 2018-05-23 14:04 UTC

**Comment by AndrzejWroGM** [comment] 2018-05-23 17:40
Hello, I have latest SQL 2017 installed and I have abowe issue with it.
