### ISSUE TITLE
Never call BuildServiceProvider

### ISSUE THREAD

**Issue by Tratcher** [dotnet-architecture/eShopOnWeb#465] opened 2020-10-06 15:29 UTC
https://github.com/dotnet-architecture/eShopOnWeb/blob/fa8839e1d8d2ce7918b8d09179a0889fe728a582/tests/FunctionalTests/Web/WebTestFixture.cs#L44

This is an anti-pattern that causes issues with the service lifetimes (e.g. it can create multiple instances of singletons).

@javiercn can you suggest a better pattern for consuming services in a WebApplicationFactory fixture?

**Comment by javiercn** [comment] 2020-10-06 16:14
Ugh, yes.

Just create an IStartupFilter and run the initialization code when it's called, you can inject dependencies to it and it only runs once when the host is being built. You can just leave the pipeline alone at that point.

https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/ForwardedHeadersStartupFilter.cs#L10-L20

**Comment by ardalis** [comment] 2020-10-06 16:38
We should make a note to update the docs, then:
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory

**Comment by ardalis** [comment] 2020-10-06 16:40
Does it help to point out that the serviceProvider in question is only used to seed the database before tests are run, and isn't part of the actual application or the app's service provider? It's literally only needed because EF needs a scope.

**Comment by javiercn** [comment] 2020-10-06 16:44
It doesn't hurt, but modifying updating the sp and the pipeline is fair game

**Comment by Tratcher** [comment] 2020-10-06 17:24
> Does it help to point out that the serviceProvider in question is only used to seed the database before tests are run, and isn't part of the actual application or the app's service provider? It's literally only needed because EF needs a scope.

I don't follow. The linked doc also resolves services like an ILogger, creating duplicate singleton logging services in an app which has caused issues in the past. In the average test app this might be harmless, but it's not a pattern we should ever recommend.

**Comment by ardalis** [comment] 2020-10-06 20:04
Fair enough and good point. We should update it there and here, then.

**Comment by fingers10** [comment] 2020-11-01 16:39
@javiercn or @Tratcher   please can you show modified example on how to rewrite code without calling `services.BuildServiceProvider()` using this eshoponweb project as example?

**Comment by Tratcher** [comment] 2020-11-01 17:24
If this were a normal app, not a test fixture, the guidance would be to move that code into Program.Main between Build and Start/Run. That way the service collection has already been built by the host, but the app hasn't fully started yet.

For a WebApplicationFactory test fixture, it looks like you need to override ` protected virtual IHost CreateHost(IHostBuilder builder)` and put this logic between Build and Start.
https://github.com/dotnet/aspnetcore/blob/584e06fcedc7f26f59d19305b68207ec982bd11a/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L371-L376

**Comment by adrianiftode** [comment] 2020-12-19 21:57
@Tratcher overriding `CreateHost` works only if the API uses the .NET Generic Host, more exactly if Program.cs has the following method
```
public static IHostBuilder CreateHostBuilder(string[] args) => Host....
```
If this method exists, then `CreateHost` is called, and thus overriding this method makes sense. I assume this happens because this is how it finds the host builder, as per these lines of [code](https://github.com/dotnet/aspnetcore/blob/584e06fcedc7f26f59d19305b68207ec982bd11a/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L147)

Once this is added the problem is I get a totally different issue, instead of resolving the in memory dbcontext, I get my testing running against the database!

**Comment by Blackclaws** [comment] 2021-11-12 11:30
With .Net 6.0 you can now no longer count on ConfigureWebHost being called at all if you're using top level statements in your main server code. This is because you are now creating a DeferredHostBuilder. This one will still get passed to CreateHost however. You can then configure it as an IWebHostBuilder by manually calling ConfigureWebHost on it.

**Comment by ardalis** [comment] 2021-12-02 21:46
@Tratcher Do you have any updated guidance on this? I would like to have this repo reflect the latest guidance for .NET 6 but [the docs for integration tests still show the pattern used in this repo for configuring and seeding data before tests](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#customize-webapplicationfactory).

If/when the docs are updated or specific changes are suggested here I'll be happy to update this but for now I'm going to close this issue since I don't see any immediate resolution forthcoming. Thanks!

**Closed by ardalis** 2021-12-02 21:46 UTC

**Comment by Tratcher** [comment] 2021-12-06 19:11
@ardalis I've filed https://github.com/dotnet/AspNetCore.Docs/issues/24204 to address this in the docs.

**Comment by ardalis** [comment] 2021-12-06 20:34
Thanks, I'm watching it. Once we have concrete guidance on how to perform data seeding without using BuildServiceProvider I'll update these samples accordingly.
