### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by bhooshan0x01** [dotnet-architecture/eShopOnWeb#513] opened 2021-02-22 09:51 UTC
While accessing the admin page, it is showing an invalid crt error for catalog-item, catalog-brands, catalog-types.

**Comment by ardalis** [comment] 2021-10-31 19:31
Hey @bhooshan0x01, I know it's been a bit since you reported this. I wasn't able to reproduce it with the latest build. If you're still seeing it can you send more detailed steps of what you're doing?

Closing for now but feel free to reopen if you have more details.

**Closed by ardalis** 2021-10-31 19:31 UTC
