### ISSUE TITLE
Unable to cast the type 'System.Int32' to type 'System.Object

### ISSUE THREAD

**Issue by JeffreyChan** [dotnet-architecture/eShopOnWeb#178] opened 2018-12-31 14:29 UTC
System.NotSupportedException: 'Unable to cast the type 'System.Int32' to type 'System.Object'. LINQ to Entities only supports casting EDM primitive or enumeration types.'

This error happened when Orderby has value in BaseSpecification class

![image](https://user-images.githubusercontent.com/5321225/50562038-8107ef80-0d4b-11e9-953b-cfff5d7f5a79.png)

**Comment by efleming18** [comment] 2019-01-02 20:47
Thanks, @JeffreyChan ! I will take a look at this, this week.

**Comment by JeffreyChan** [comment] 2019-01-07 11:44
Thanks a lot. I think it's a bug in EF.

**Comment by efleming18** [comment] 2019-03-10 00:11
Hey @JeffreyChan - sorry for the delayed response on this. I am actually unable to reproduce this. Would you be able to send me the steps to reproduce it using the UI? Or the steps you took to get this error?

**Comment by JeffreyChan** [comment] 2019-03-24 08:22
> Hey @JeffreyChan - sorry for the delayed response on this. I am actually unable to reproduce this. Would you be able to send me the steps to reproduce it using the UI? Or the steps you took to get this error?
Hi @efleming18 , sorry for the delayed response on this.
someone in stackoverflow already help me fix this problem.
you can check this [link](https://stackoverflow.com/questions/53985059/unable-to-cast-the-type-system-int32-to-type-system-object-during-ef-code-fir) out, find more details.

**Comment by efleming18** [comment] 2019-03-24 17:49
Awesome @JeffreyChan ! I am glad they were able to help you with the issue. I'm going to close it on this side, but if you have any more questions let us know.

**Closed by efleming18** 2019-03-24 17:49 UTC
