### ISSUE TITLE
Unable to login - Google Chrome > 80

### ISSUE THREAD

**Issue by syslog76** [dotnet-architecture/eShopOnWeb#361] opened 2020-03-24 17:25 UTC
Google Chrome starting version 80 reject insecure SameSite=None cookies
More: https://chromestatus.com/feature/5633521622188032

To solve this problem:
- options.MinimumSameSitePolicy = SameSiteMode.None;
+ options.MinimumSameSitePolicy = SameSiteMode.Strict;

**Comment by efleming18** [comment] 2020-04-08 14:56
Hey @syslog76  - I am unable to reproduce this, which led me to do a little research. 

These changes are outlined here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.0-3.1
with an announcement here that also describes the changes:  ttps://github.com/dotnet/aspnetcore/issues/14996

From what I gather, there would be issues logging in, in versions of Chrome 75 or less but having `options.MinimumSameSitePolicy = SameSiteMode.None;` should work for versions of Chrome 78+. 

If you're still having issues could you post the steps you're taking and a snippet of the error you're receiving?

**Comment by efleming18** [comment] 2020-04-29 19:11
Hey @syslog76 - I'm going to close this for now. If you're still having issues though, please let me know with repro steps.

**Closed by efleming18** 2020-04-29 19:11 UTC
