### ISSUE TITLE
Questions on general architecture (complex queries)

### ISSUE THREAD

**Issue by alexanderbikk** [dotnet-architecture/eShopOnWeb#203] opened 2019-02-02 16:30 UTC
Hello! Very nice project, thank you guys! I have read a lot of discussions in comments and clarify many things for myself. But I still have one question related to current structure of project.

What if I need complex queries using Joins and/or GroupJoins for some complex pages for example or reports? 
Earlier I had structure like Repos -> Services -> UI. My repos return the IQueryable and then Services implemented all complex queries and returned Domain models. Then UI converts all to ViewModel objects. But seem like return the IQueryable from repos is not very good idea.
According to your project structure should I add specific repository for my needs like you did with OrderRepository and implement all complex queries there? I guess functionality in SpecificationEvaluator won't be enough and sometimes the Includes not the best choice I think.
Of course I can use stored procedures for reports or maybe add Dapper if I need better performance. But I want to understand where is better to implement some complex queries  for some business requirements.

Thanks in advance

**Comment by fiseni** [comment] 2019-02-02 17:19
The SpecEvaluator indeed doesn't offer the possibility for complex queries. In my own projects I enrich the evaluator with few additional options which I consider crucial. @ardalis if you find them useful I can prepare PR.
- Select option. It's quite useful, especially while querying many-to-many relations.
- AsNoTracking option. It might increase the speed of read-only queries.
- DBSet.Load option. This is somewhat same as Include, except there is a DB hit for each Load() and the query is simple select. In case you have more 3-4 Includes, then the generated nested query becomes nasty. Depending on the situation, sometimes using Load instead of Include might give better performance.
- AddCriteria option. Instead of criteria passed as constructor argument, we can add several where criterias in the body. It look much cleaner, and it offers adding criteria based on some condition.
- Min, max, sum option.

But, on the other hand we should know how much is too much, otherwise you'll end up replicating all DBSet functionalities :) 
So, we should draw a line, and everything that can't be achieved through the defined set of options, you just create specific repository and work directly with the DBContext.

**Comment by alexanderbikk** [comment] 2019-02-02 17:45
I totally agree with you that  we should draw a line between using SpecEvaluator abstraction and re-creating the existing functionality :)
Finally I see your point thanks, @fiseni

**Comment by alexanderbikk** [comment] 2019-02-03 09:39
Hi, @fiseni I thought more about SpecificationEvaluator. And have another question can the SpecificationEvaluator will be a bottleneck in big projects? Since we alway call the sepc method GetQuery which build our query. What is your experience of using this pattern? 

Also about the complex logic into the Repositories. What if I want to return mixed results like in DTO models from separate repository? I mean what if my result from the repository have no specific model in my Domain models, should I create additional Complex model in Core project, populate it in Repo and then map my complex Entity  to DTO in Service/UI layer?

Examples:
1. Repo(select 2+ tables and build Complex model) -> Service(map to DTO + some business layer logic) -> UI
2. Repo(select 2+ tables and build Complex model) ->  UI(map to DTO)

I see the other way when I can build my DTO objects in service layer by calling a couple of repositories but in this case I will have more that 1 call to DB.

Thanks

**Comment by fiseni** [comment] 2019-02-03 11:44
Hi,

Before I answer, I wanna note that @ardalis is the owner of the project. He has more experience with this structure and can provide you with more detailed and valuable answers. I just liked the project and I try to contribute occasionally, so not necessarily my answers are absolutely right.

Don't get stuck too much to the SpecificationEvaluator. It was just a convenient way to take that logic out of the base repository to a separate utility class. Specification pattern in essence predicates passing the predefined queries as objects. You have a query that you will be using often in your app, so you define a class which contains all the information for building that particular query, and then you instantiate it and moving it around as you like. That's the whole idea. Somewhat same approach is used in CQRS pattern (MediatR is popular implementation). Regarding the performance, I don't think there will be any drawbacks, since queries are not evaluated at that stage. In fact, even if you don't use this approach, the same process is done implicitly in the background. We just expressed it explicitly and attached a name to it.

Should you create complex models in core? I think there is a misconception of what "domain model" means. Usually the "model" term is understood as a set of entities or data classes which will be persisted. In contrary, "data model" encompasses entities, value objects (immutable data), data classes which are not persisted, even structures that define behavior (services, utilities). All of these structures are used to mimic and describe a particular business domain, simply said we are modeling the business domain (thus the term "domain model").
I assume, the question then is do you place these derived (complex) data classes in the core, or you place them in the app or UI layer. Well, once again you analyze if those structures belong to the domain model, do they anyhow help describing the business model? I admit, sometimes this is the hardest part. But, you can start by analyzing where is the intended usage of these classes. Will they be utilized in the business logic, simply in UI, etc?
At last, leave the performance fine tuning for the later stages. Making assumptions is not the best approach. You can have few DB hits by calling several repositories, it's OK. Here you might want to research the aggregate roots, repository per aggregate root and similar concepts.

Cheers.

**Comment by alexanderbikk** [comment] 2019-02-03 12:34
Thanks a lot @fiseni  I got all answers :)

**Comment by ardalis** [comment] 2019-02-03 13:46
Sorry to hop in here late. @fiseni did a great job in his last response. A few of my own thoughts to add on here:

1. I usually separate reporting functionality from my application functionality. Reports tend to be read-only and don't tend to need to use the functionality of the domain model at all. Often the most efficient and effective way to gather data for reports is by bypassing the domain model used by the application and going directly to the database. I would certainly never advocate that someone try and use a DDD model to do data warehousing or BI or "bigdata" style analytics of the persisted data from the application. Likewise, EF (and other ORMs) is meant to make it easy to track and modify relatively small numbers of entities in memory. When you want to do large amounts of data aggregation and manipulation in a purely readonly fashion, you don't need EF's tracking capabilities and you'll almost certainly be better-served by using a language like SQL in these scenarios, IME.

2. Given point 1, I almost always limit my repositories to only return domain entities and ideally just aggregates assuming I'm using the aggregate pattern.

3. But what if I need some custom type, a DTO, etc? Usually the reason why I need a DTO is because of a specific use case, almost always driven by the UI layer. In these cases, I'll perform mapping from the domain model (entities + value objects etc) to whatever DTOs the UI layer requires. I pretty much never put this into a Repository since it breaks SRP. Repository is simply responsible for persisting and fetching entities/aggregates. Not mapping to this or that DTO - that's a separate responsibility.

I do think the SpecificationEvaluator that's been developed in this project is very nice and I have been using variations of it on other projects. I think it may make sense to pull that out into its own separate project and Nuget package at some point, assuming doing so wouldn't limit too much how people could use it.

Closing this since it sounds like @alexanderbikk has his answers. Feel free to comment further if you have questions.

**Closed by ardalis** 2019-02-03 13:46 UTC

**Comment by fiseni** [comment] 2019-02-03 14:39
Hi @ardalis 

Now, I have a question :) I totally agree with everything, and actually I have been using the same approach for years, I kept reporting separate. But, lately I doubt that idea. No matter how careful you are while designing the domain model and the DB structure, you always end up with some implicit rules, silent conventions how the data should be read or what particular set of data means. You have few tags here and there, some implicit rules in your head, etc. As long all these imperfections get encapsulated behind the domain model, it's totally fine I guess, the interface is clean anyway. But, when you have to replicate all that in SQL for reporting, then you end up with "duplicate" logic, which of course should be maintained and evolved in parallel way. And, that bothers me.
Disabling tracking on EF6 was really painful, since it was done per query basis. But, finally on EFCore that can be done on DBContext level (context.ChangeTracker.QueryTrackingBehavior), and by my experience I get surprisingly good results.
Once again, I'm talking for a "simple" reporting. I'm not tackling warehousing, BI, analytical cubes.. which yea is different subject on different level.

I would love to hear your thoughts, or read a blog on this subject.
Thanks.

**Comment by ardalis** [comment] 2019-02-03 15:02
I'm pragmatic and like to follow what I call [pain driven development](http://www.weeklydevtips.com/010). For me, writing reports with any amount of complexity (even just joins) was always easier for me in SQL than in EF/LINQ. That may just be my background/skills. I understand what you're saying about this bypassing domain rules but in practice I don't recall this ever being an issue for me. Likewise the `AsNoTracking` functionality being per-query hasn't been a big problem for me, either, since it's usually only a scant few queries where I want to use that, not whole dbContexts (in my experience).

That said, if you're finding success building reports using EF/EF Core and LINQ by all means keep doing that. It's working for you. If it starts to become painful, my recommendation will be to drop down to writing your own SQL, but only because that's what has worked well for me.

**Comment by ardalis** [comment] 2019-02-03 21:02
Right, I'm not 100% happy with how CatalogService is working in the existing app to be honest. I kind of inherited the way things are working and I haven't yet refactored it to something I like better. The crux of the problem is what you're describing - where do you put a service whose job it is to produce a UI-specific ViewModel or DTO such that the solution doesn't get cluttered by its dependencies? One option of course is to put the DTO(s) into the Core/ApplicationCore project and then you can put the service anywhere you want. Since the DTOs should be just POCOs, this isn't that awful, but it's always rubbed me the wrong way since it's kind of "polluting" the domain model project with things that are purely UI concerns (even if they don't depend on UI types). If you don't do this, or something similar (create a DTOs project), you can't put the service in an Infrastructure project. At that point, the only remaining option is to put the types and the services that produce them in the UI project. Which is what you see today in eShopOnWeb. To me it's the least ugly of the available options, but this is to some extent a matter of taste I admit.

In your last question of what to do if you have some custom query that returns some type that isn't defined in your domain model, you're even more constrained. This query really must go into Infrastructure IMO, and that means that its return type must be defined somewhere both Infrastructure and UI projects can get to it. That means it must go into the Core project or some similar project. In this case I would put the type into Core again because there's no really a better option.

Now in reading this, I'm left to wonder what's the difference between these two approaches, since I'm saying in one case I'd put everything in the UI project and in another to use Core and Infrastructure. I think the main difference to me is in whether the work in question is just wrapping up some existing repositories and entities and building a DTO from these, or if the work in question is executing a custom query and directly returning the result. The first one is a service that depends on repositories and entities, the second one is a data access class that presumably knows about the implementation details of querying some data source and thus belongs in infrastructure.

Does that help?

**Comment by alexanderbikk** [comment] 2019-02-04 09:35
Hi @ardalis sorry for delay it was midnight in my country  :)

My question was about the second approach that you described "the work in question is executing a custom query and directly returning the result". And yes it helps to me and the solution here is " it must go into the Core project or some similar project." 

About the first aapproach I agree with your and I like your solution to put the UI specific services in the UI directly since we "just wrapping up some existing repositories and entities and building a DTO from these". The only cons that  I see here is that we can have CatalogService both in UI and in Core so sometimes it can be misunderstanding for new developers in project etc. 

After 3 days research of  "Clean architecture", "Repos+ UOW vs Queries" and  how to refactor my current approach I have found the solution.

Thanks a lot!
